---
- hosts: all
  become: true
  tasks:

  - name: Copy image pull script
    copy: 
      src: pull-k8s-image.sh
      dest: /tmp/pull-k8s-image.sh
      mode: '0777'

  - name: Pull the blocked Kubernetes image
    command: /tmp/pull-k8s-image.sh

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --kubernetes-version=v1.18.6 --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}"  --node-name master --pod-network-cidr=10.179.0.0/16
    become: yes

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Copy calico.yaml
    copy: 
      src: calico.yaml
      dest: /tmp/calico.yaml

  - name: Install calico pod network
    become: false
    command: kubectl apply -f /tmp/calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    become: no
  
  - name: fetch kube config
    fetch: 
      src: /home/vagrant/.kube/config 
      dest: ./kube-config
    become: no

