---
- hosts: all
  become: true
  tasks:
  - name: Replace Apt source to Aliyun
    replace:
      path: /etc/apt/sources.list
      regexp: 'archive.ubuntu.com'
      replace: 'mirrors.aliyun.com'

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - wget
      - vim
      - nginx